name: Update Member IDs Otomatis

on:
  push:
    branches: [ main ]
    paths:
      - 'member.json'

jobs:
  update-ids:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update daftar ID
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Ambil file asli dari GitHub
          curl -sSL https://raw.githubusercontent.com/yuwanaroy-cpu/password/main/member.json > temp.json

          # Update password
          jq '.password = "cimangcuvip"' temp.json > updated.json

          # Validasi JSON
          jq . updated.json > member.json

          rm temp.json

          # Commit jika ada perubahan
          if git diff --quiet member.json; then
            echo "Tidak ada perubahan"
            exit 0
          else
            git add member.json
            git commit -m "Autoupdate member IDs"
            git push
            echo "✅ Berhasil di-update!"
          fi
